export const styles = {
  container: {
    minHeight: "100vh",
    background: "linear-gradient(135deg, var(--bg-root) 0%, var(--bg-solid-card) 100%)",
    padding: "24px",
  },
  header: {
    maxWidth: "900px",
    margin: "0 auto 24px",
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  backButton: {
    padding: "8px 16px",
    background: "var(--accent-bg)",
    color: "#a5b4fc",
    border: "1px solid var(--accent-bg-hover)",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "500",
    transition: "all 0.3s ease",
  },
  title: {
    fontSize: "28px",
    fontWeight: "700",
    color: "var(--text-primary)",
    margin: 0,
  },
  content: {
    maxWidth: "900px",
    margin: "0 auto",
    display: "flex",
    flexDirection: "column" as const,
    gap: "24px",
  },
  form: {
    width: "100%",
  },
  inputSection: {
    background: "var(--bg-solid-card-85)",
    borderRadius: "16px",
    padding: "24px",
    border: "1px solid var(--border-dark)",
  },
  label: {
    display: "block",
    fontSize: "14px",
    fontWeight: "600",
    color: "var(--text-tertiary)",
    marginBottom: "8px",
    flex: 1,
  },
  input: {
    width: "100%",
    padding: "12px",
    background: "var(--bg-glass-80)",
    border: "1px solid var(--border-dark-80)",
    borderRadius: "12px",
    color: "var(--text-secondary)",
    fontSize: "14px",
    marginBottom: "16px",
    boxSizing: "border-box" as const,
  },
  select: {
    width: "100%",
    padding: "12px",
    background: "var(--bg-glass-80)",
    border: "1px solid var(--border-dark-80)",
    borderRadius: "12px",
    color: "var(--text-secondary)",
    fontSize: "14px",
    marginBottom: "16px",
    cursor: "pointer",
    boxSizing: "border-box" as const,
  },
  inputRow: {
    display: "flex",
    gap: "16px",
  },
  characterList: {
    background: "var(--bg-glass-80)",
    border: "1px solid var(--border-dark-80)",
    borderRadius: "12px",
    padding: "12px",
    marginBottom: "16px",
    maxHeight: "200px",
    overflowY: "auto" as const,
  },
  noCharacters: {
    color: "#64748b",
    fontSize: "14px",
    textAlign: "center" as const,
    padding: "20px",
    margin: 0,
  },
  characterCheckbox: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "10px",
    background: "var(--bg-card-60)",
    borderRadius: "8px",
    marginBottom: "8px",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  checkbox: {
    width: "18px",
    height: "18px",
    cursor: "pointer",
  },
  characterName: {
    color: "var(--text-secondary)",
    fontSize: "14px",
  },
  button: {
    width: "100%",
    padding: "14px 24px",
    background: "linear-gradient(135deg, var(--accent-primary) 0%, #8b5cf6 100%)",
    color: "white",
    border: "none",
    borderRadius: "12px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.3s ease",
  },
  streamingSection: {
    background: "var(--bg-solid-card-85)",
    borderRadius: "16px",
    padding: "24px",
    border: "1px solid var(--border-dark)",
  },
  sectionTitle: {
    fontSize: "18px",
    fontWeight: "600",
    color: "var(--text-secondary)",
    margin: "0 0 16px",
  },
  streamingContent: {
    background: "var(--bg-glass)",
    borderRadius: "12px",
    padding: "20px",
  },
  streamingText: {
    color: "#a78bfa",
    fontSize: "14px",
    lineHeight: "1.8",
    whiteSpace: "pre-wrap" as const,
    wordBreak: "break-word" as const,
  },
  typingIndicator: {
    display: "inline-block",
    marginRight: "8px",
    animation: "pulse 1s infinite",
  },
  resultSection: {
    background: "var(--bg-solid-card-85)",
    borderRadius: "16px",
    padding: "24px",
    border: "1px solid var(--border-dark)",
  },
  resultContent: {
    maxHeight: "600px",
    overflowY: "auto" as const,
    paddingRight: "8px",
  },
  resultText: {
    background: "var(--bg-glass-80)",
    padding: "24px",
    borderRadius: "12px",
    color: "var(--text-tertiary)",
    fontSize: "14px",
    lineHeight: "1.6",
    whiteSpace: "pre-wrap" as const,
    wordBreak: "break-word" as const,
    overflowX: "auto" as const,
  },
};
