export const styles = {
  container: {
    minHeight: "100vh",
    background: "var(--bg-root)",
  },
  nav: {
    background: "var(--bg-solid-card-85)",
    backdropFilter: "blur(12px)",
    borderBottom: "1px solid var(--border-dark)",
    padding: "0 32px",
    position: "sticky" as const,
    top: 0,
    zIndex: 99999,
  },
  navContent: {
    maxWidth: "1400px",
    margin: "0 auto",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "16px 0",
    flexWrap: "wrap" as const,
  },
  logo: {
    fontSize: "24px",
    marginRight: "24px",
    fontWeight: "700",
    color: "var(--text-primary)",
    cursor: "pointer",
    transition: "transform 0.2s ease",
  },
  scenarioContainer: {
    display: "flex",
    gap: "4px",
    background: "var(--bg-glass)",
    padding: "4px",
    borderRadius: "12px",
    marginLeft: "auto",
  },
  scenarioBtn: (active: boolean) => ({
    padding: "6px 16px",
    borderRadius: "8px",
    border: "none",
    background: active
      ? "linear-gradient(135deg, var(--accent-primary) 0%, #8b5cf6 100%)"
      : "transparent",
    color: active ? "#ffffff" : "var(--text-muted)",
    cursor: "pointer",
    fontWeight: active ? "600" : "400",
    transition: "all 0.2s ease",
    fontSize: "13px",
  }),
  mainPage: {
    maxWidth: "1000px",
    margin: "0 auto",
    padding: "32px",
  },
  chatSection: {
    background: "var(--bg-solid-card-85)",
    border: "1px solid var(--border-dark)",
    borderRadius: "20px",
    padding: "32px",
    marginBottom: "24px",
  },
  chatTitle: {
    fontSize: "28px",
    fontWeight: "700",
    marginBottom: "8px",
    color: "var(--text-primary)",
    margin: 0,
  },
  chatSubtitle: {
    color: "var(--text-muted)",
    marginBottom: "24px",
  },
  inputForm: {
    display: "flex",
    gap: "12px",
  },
  input: {
    flex: 1,
    padding: "14px 20px",
    border: "2px solid var(--border-dark)",
    borderRadius: "12px",
    background: "var(--input-bg)",
    color: "var(--text-primary)",
    fontSize: "15px",
    boxSizing: "border-box" as const,
  },
  submitButton: {
    padding: "14px 28px",
    background: "linear-gradient(135deg, var(--accent-primary) 0%, #8b5cf6 100%)",
    color: "white",
    border: "none",
    borderRadius: "12px",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "15px",
  },
  historySection: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "16px",
  },
  message: {
    border: "1px solid var(--border-dark)",
    borderRadius: "16px",
    padding: "20px 24px",
  },
  messageRole: {
    fontWeight: "600",
    marginBottom: "12px",
  },
  messageContent: {
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap" as const,
  },
  dataSection: {
    marginTop: "16px",
  },
  summary: {
    color: "var(--text-muted)",
    cursor: "pointer",
  },
  dataContent: {
    marginTop: "12px",
  },
  rawData: {
    padding: "16px",
    background: "var(--bg-glass)",
    borderRadius: "8px",
    fontSize: "13px",
    color: "var(--text-muted)",
    overflow: "auto" as const,
    margin: 0,
  },
};
